BUCKET_ID="big-data-lab-141317"
hadoop fs -copyToLocal gs://$BUCKET_ID/us-accidents.zip
unzip us-accidents.zip
hadoop fs -mkdir -p input/us-accidents
hadoop fs -copyFromLocal us-accidents/* input/us-accidents

spark-submit --class CreateTable --master yarn --num-executors 1 --driver-memory 512m --executor-memory 512m --executor-cores 1 --packages io.delta:delta-core_2.12:1.0.0 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog us-accidents-warehouse_2.12-1.0.0.jar
spark-submit --class SurroundingLoader --master yarn --num-executors 1 --driver-memory 512m --executor-memory 512m --executor-cores 1 --packages io.delta:delta-core_2.12:1.0.0 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog us-accidents-warehouse_2.12-1.0.0.jar
spark-submit --class TemperatureLoader --master yarn --num-executors 1 --driver-memory 512m --executor-memory 512m --executor-cores 1 --packages io.delta:delta-core_2.12:1.0.0 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog us-accidents-warehouse_2.12-1.0.0.jar
spark-submit --class VisibilityLoader --master yarn --num-executors 1 --driver-memory 512m --executor-memory 512m --executor-cores 1 --packages io.delta:delta-core_2.12:1.0.0 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog us-accidents-warehouse_2.12-1.0.0.jar
spark-submit --class WeatherConditionLoader --master yarn --num-executors 5 --driver-memory 512m --executor-memory 512m --executor-cores 4 --packages io.delta:delta-core_2.12:1.0.0 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog us-accidents-warehouse_2.12-1.0.0.jar input/us-accidents
spark-submit --class TimeLoader --master yarn --num-executors 4 --driver-memory 512m --executor-memory 512m --executor-cores 1 --packages io.delta:delta-core_2.12:1.0.0 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog us-accidents-warehouse_2.12-1.0.0.jar input/us-accidents
spark-submit --class LocationLoader --master yarn --num-executors 5 --driver-memory 512m --executor-memory 512m --executor-cores 4 --packages io.delta:delta-core_2.12:1.0.0 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog us-accidents-warehouse_2.12-1.0.0.jar input/us-accidents
spark-submit --class FactLoader --master yarn --num-executors 5 --driver-memory 512m --executor-memory 512m --executor-cores 4 --packages com.swoop:spark-alchemy_2.12:1.1.0,io.delta:delta-core_2.12:1.0.0 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog us-accidents-warehouse_2.12-1.0.0.jar input/us-accidents
